---
- name: Устанавливаем пакет bridge-utils
  become: true
  ansible.builtin.apt:
    name:
      - bridge-utils
    update_cache: true
    cache_valid_time: 3600

- name: Копируем настройки сетевого моста
  become: true
  ansible.builtin.template:
    src: default_config_bridge.j2
    dest: /etc/network/interfaces.d/interface-vmbr0
    mode: '644'
  when: ansible_default_ipv4.interface != 'vmbr0'
  register: previous_task

- name: Перезагружаем сервер
  become: true
  ansible.builtin.reboot:
  when: previous_task.changed
